import { createHash } from 'node:crypto';
import { BudgetStoreError, type BudgetState, type BudgetStore, type NewSession, type NewUser, type StoredSession, type StoredUser } from './budget-store.ts';
import { PersistenceError } from './financial-store.ts';
import { calculateAccountBalances, oldestAccount } from '../planning/engine.ts';
const digest = (value: unknown) => createHash('sha256').update(JSON.stringify(value)).digest('hex');
export class InMemoryBudgetStore implements BudgetStore {
  private readonly users = new Map<string, StoredUser>(); private readonly sessions = new Map<string, StoredSession>(); private readonly budgets = new Map<string, BudgetState>(); private readonly receipts = new Map<string, Map<string, { payloadDigest: string; result: unknown }>>(); private readonly queues = new Map<string, Promise<unknown>>();
  createUser(user: NewUser) { if (this.users.has(user.email)) throw new BudgetStoreError('CONFLICT', 'Account already exists'); this.users.set(user.email, { ...user }); }
  findUser(email: string) { return this.users.get(email) ? { ...this.users.get(email)! } : null; }
  findUserById(id: string) { const user = [...this.users.values()].find(candidate => candidate.id === id); return user ? { ...user } : null; }
  createSession(session: NewSession) { this.sessions.set(session.tokenHash, { userId: session.userId, expiresAt: session.expiresAt, revoked: false }); }
  findSession(tokenHash: string) { const session = this.sessions.get(tokenHash); return session ? { ...session } : null; }
  revokeSession(tokenHash: string) { const session = this.sessions.get(tokenHash); if (session) session.revoked = true; }
  createBudget(ownerId: string, state: BudgetState) { const user = this.findUserById(ownerId); if (!user) throw new BudgetStoreError('NOT_FOUND'); if (user.budgetId) throw new BudgetStoreError('CONFLICT', 'A user can own only one budget'); this.budgets.set(state.id, this.clone(state)); this.users.set(user.email, { ...user, budgetId: state.id }); return this.clone(state); }
  loadBudget(ownerId: string, budgetId: string) { const user = this.findUserById(ownerId); const state = user?.budgetId === budgetId ? this.budgets.get(budgetId) : undefined; return state ? this.clone(state) : null; }
  saveBudget(ownerId: string, state: BudgetState) { if (!this.loadBudget(ownerId, state.id)) throw new BudgetStoreError('NOT_FOUND'); this.budgets.set(state.id, this.clone(state)); return this.clone(state); }
  async executeFinancial<T>(command: any): Promise<{ result: T; version: number }> {
    const previous = this.queues.get(command.budgetId) ?? Promise.resolve();
    const run = previous.then(() => this.executeFinancialNow<T>(command), () => this.executeFinancialNow<T>(command));
    this.queues.set(command.budgetId, run);
    try { return await run; } finally { if (this.queues.get(command.budgetId) === run) this.queues.delete(command.budgetId); }
  }
  private async executeFinancialNow<T>(command: any): Promise<{ result: T; version: number }> { let state = this.loadBudget(command.ownerId, command.budgetId); if (!state && command.seed) state = this.createBudget(command.ownerId, command.seed); if (!state) throw new PersistenceError('NOT_FOUND', 'Resource not found'); const receipts = this.receipts.get(state.id) ?? new Map(); this.receipts.set(state.id, receipts); const payloadDigest = digest({ command: command.command, input: command.input, expectedVersion: command.expectedVersion }); const receipt = receipts.get(command.idempotencyKey); if (receipt) { if (receipt.payloadDigest !== payloadDigest) throw new PersistenceError('CONFLICT', 'Idempotency key was reused with a different payload'); return { result: receipt.result as T, version: state.version }; } if (command.expectedVersion !== undefined && command.expectedVersion !== state.version) throw new PersistenceError('CONFLICT', 'Budget version is stale'); const events = state.events.map((event: any) => ({ ...event })); const result = command.work(state, events, state.version + 1); state.events = events; state.version += 1; this.saveBudget(command.ownerId, state); receipts.set(command.idempotencyKey, { payloadDigest, result }); return { result, version: state.version }; }
  async loadFinancial(ownerId: string, budgetId: string) { const state = this.loadBudget(ownerId, budgetId); if (!state) throw new PersistenceError('NOT_FOUND', 'Resource not found'); return state; }
  private clone(state: BudgetState): BudgetState { const events = state.events.map(event => ({ ...event, payee: event.payee ?? null, memo: event.memo ?? null })); const source = state.accounts?.length ? state.accounts : (state.account ? [{ ...state.account, kind: state.account.kind ?? 'CASH', archived: state.account.archived ?? false }] : []); const accounts = calculateAccountBalances(source, events.filter(event => ['INCOME', 'SPENDING', 'TRANSFER_OUT', 'TRANSFER_IN'].includes(event.kind)).map(event => ({ accountId: event.accountId, kind: event.kind as 'INCOME' | 'SPENDING' | 'TRANSFER_OUT' | 'TRANSFER_IN', amountMinor: event.amountMinor }))); const alias = oldestAccount(accounts); return { ...state, account: alias ? { id: alias.id, name: alias.name, openingBalanceMinor: alias.openingBalanceMinor, archived: alias.archived, kind: alias.kind, createdAt: alias.createdAt } : null, accounts, transfers: (state.transfers ?? []).map(transfer => ({ ...transfer, payee: transfer.payee ?? null, memo: transfer.memo ?? null })), categories: state.categories.map(category => ({ ...category })), events }; }
}
export class InMemoryFinancialStore { private readonly store: InMemoryBudgetStore; constructor(store: InMemoryBudgetStore) { this.store = store; } execute<T>(command: any) { return this.store.executeFinancial<T>(command); } load(ownerId: string, budgetId: string) { return this.store.loadFinancial(ownerId, budgetId); } }
